# Generated by Django 5.1.3 on 2024-11-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0003_remove_category_papers_cate_name_709915_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["name"], name="papers_cate_name_709915_idx"),
        ),
    ]
